
spring:
  profiles:
    include: login
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.38.88.242:3306/angrybox4?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mymysql
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: 184.72.42.251 # 127.0.0.1
    password: myredis
    port: 6379
    lettuce: #jedis : 별도 의존성 필요 / lettuce : 별도 설정 필요 없음, 비동기로 요청을 처리(Netty)
      pool:
        max-active: 8 #pool에 할당할 수 있는 커넥션 최대수
        max-idle: 10 #pool의 "idle" 커넥션 최대 수
        min-idle: 2 #pool에서 관리하는 idle 커넥션의 최소 수

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.teamY.angryBox.vo, com.teamY.angryBox.dto
  mapper-locations: mybatis-mapper/*.xml
